### ISSUE TITLE
Could we have more details in documentation?

### ISSUE THREAD

**Issue by sangdth** [EvanAgee/vuejs-wordpress-theme-starter#1]
This is great work, I love the idea so much. But I'm so new to Vue and also Vuex, could you please have more detail about it in documentation?

Thanks in advance.

**Comment by EvanAgee** [comment]
Absolutely, let me work on that!

**Comment by EvanAgee** [comment]
@sangdth I've added a few more notes to the documentation for newcomers to Vue! Please let me know if there are specific questions you have, I'd be happy to answer them.

**Comment by sangdth** [comment]
Thank you for you help, @EvanAgee 

I can get page's content by using the `getPages()` you created in `/api`, is it right way to do?
````
api.getPages((pages) => {
    this.pages = pages;
});
````

Now I want to fetch the posts, but it does not work as expect :D I look at the `/api` folder, can not find it, so I tried to copy, something like:
````
getPosts(cb) {
    axios
        .get(window.SETTINGS.API_BASE_PATH + 'posts')
        .then((response) => {
            cb(response.data);
        })
        .catch((e) {
            cb(e);
        });
}
````
Please help.
I'm still learning, so maybe there are some 'got cha' mistakes.

**Comment by EvanAgee** [comment]
Let me make a few additions to the repo and it should help clear some things up!

**Comment by EvanAgee** [comment]
You're totally on the right track by the way, you're just running into things I had already planned to add into the project ;)

**Comment by EvanAgee** [comment]
Awesome! Is it Maximillian's course by chance? I went through the same one and it's great!

**Comment by sangdth** [comment]
Thanks, I will pull and check it out.

And yes! That is Maxi's course, I like how he explains everything in exciting way. :D
