### ISSUE TITLE
demo?

### ISSUE THREAD

**Issue by nise** [EvanAgee/vuejs-wordpress-theme-starter#10]
Is there a demo available to experience the look and feel?

**Comment by raisiqueira** [comment]
Hi, @nise. Are you having trouble running the project locally?

**Comment by EvanAgee** [comment]
Hey @nise I hadn't thought about it, mostly because there's nothing too visual about this project. This is a starting point for someone to develop a Wordpress theme based on Vuejs and truthfully it's ugly out of the box ;)
