### ISSUE TITLE
Where does /src/api/index.js get included from?

### ISSUE THREAD

**Issue by simplenotezy** [EvanAgee/vuejs-wordpress-theme-starter#100]
I can't seem to find where api/index.js is getting imported/included. Is it still being used? It is inside the /dist/ folder, but don't know how.

**Comment by EvanAgee** [comment]
@simplenotezy it's being loaded directly into the Vuex modules that need it, see https://github.com/EvanAgee/vuejs-wordpress-theme-starter/blob/master/src/store/modules/user.js for example.

**Comment by simplenotezy** [comment]
You're right; thanks @EvanAgee
