### ISSUE TITLE
npm run production error

### ISSUE THREAD

**Issue by mrKorg** [EvanAgee/vuejs-wordpress-theme-starter#11]
Hi!
Thank You for your work.
Help solve the problem.
I run 'npm run production' and get the error

> Uncaught TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (manifest.js:55)
    at Object.eslX (app.js:6)
    at __webpack_require__ (manifest.js:55)
    at Object.0 (app.js:1)
    at __webpack_require__ (manifest.js:55)
    at webpackJsonpCallback (manifest.js:26)
    at app.js:1

in manifest.js:
// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);

How I can fix it?

**Comment by NikoPeltoniemi** [comment]
Can you be a bit more specific with your problem? Did you run into any errors while runnin npm install?

**Comment by mrKorg** [comment]
I used this package to develop the site, had no problems at all, this problem arose only when it came time to run the site in production. 
npm run dev & npm run watch work without errors

**Comment by NikoPeltoniemi** [comment]
Try to run it with the --verbose -flag.

**Comment by mrKorg** [comment]
Thank you! This solved the problem.

**Comment by raisiqueira** [comment]
Close issue, please.
