### ISSUE TITLE
Font loading 

### ISSUE THREAD

**Issue by meerzulee** [EvanAgee/vuejs-wordpress-theme-starter#112]
I am using tailwindcss. When I change default font to custom one, the wordpress  doesn't load it

**Comment by EvanAgee** [comment]
@meerzulee are you also enqueing the custom font?

**Comment by meerzulee** [comment]
Yes, I tried couple rules for webpack, but no results. I solved problem using font CDN.

**Comment by sotoyjuan** [comment]
@EvanAgee you mean enqueing via wordpress theme?

**Comment by harrisonfm** [comment]
I was able to add .woff fonts without enqueueing. Webpack loads these files (confirm in loaders/fonts.js) and you can do standard @font-face in .css to include them.
