### ISSUE TITLE
Body Not Rendering

### ISSUE THREAD

**Issue by robwelan** [EvanAgee/vuejs-wordpress-theme-starter#12]
On OSX, I have loaded the starter into a MAMP [v4.2.1 (852)] instance. I have run 'npm run watch' and also 'npm run production'. In both cases, the 'header' and 'footer' render, but the body does not. Suggestions? I have fixed a minor issue with the API route (I was getting 404 errors, but I fixed this with a small edit to the app.js (I removed the leading '/'). Calling the api directly from the browser URL works fine (in my case it is 'http://localhost:8888/development-vue/wp-json/wp/v2/categories?sort=name&hide_empty=true&per_page=50').

**Comment by raisiqueira** [comment]
Hi, @robwelan. How are your permanent links? If you are using de WordPress default, change to any other permalink.

**Comment by robwelan** [comment]
I've cycled through all permalink options except for custom. No change unfortunately. In case this helps, this is the html that is rendered between the header and footer sections: '<div class="page-content-wrapper"></div>'

**Comment by robwelan** [comment]
<div class="page-content-wrapper"></div>

**Comment by robwelan** [comment]
I've worked out that adding '/development-vue' to my 'base' route (line 19 in index.js in the router folder) helps a little bit. I may need to undo my first idea (removing leading '/' in app.js).

**Comment by raisiqueira** [comment]
So it worked? 🤔

**Comment by robwelan** [comment]
Yes, with the change I've described (adding window.location.pathname if it does not equal to '' on the router/index.js and the app.js files)

**Comment by raisiqueira** [comment]
Close issue, please 😄

**Comment by EvanAgee** [comment]
Thanks so much @raisiqueira for helping out! +1 to awesomeness for you!

**Comment by Ivanok** [comment]
Hello, I'm trying to use the starter theme but i'm not able to render the body either. 

Specifically, When I open the example Home page, the lists of pages and posts are not rendering on the page.

I tried making the changes as stated above, but the list of posts is still not rendering. I am able to access the api via browser so I'm not sure what is going on. 

Thank you for making the starter theme and I hope that you'll be able to help me!

**Comment by wester97** [comment]
Any console errors?

**Comment by Ivanok** [comment]
No console errors.

**Comment by wester97** [comment]
Is the response in Inspector > Network empty? 404?

**Comment by Ivanok** [comment]
There is no 404 at all.

**Comment by wester97** [comment]
So maybe there IS a response (200)?
Did you make any changes? No weird CORS type messages? Could you paste the
request with headers, and the response? Say, for the posts requests.

**Comment by Ivanok** [comment]
I don't see the posts requests on the list at all.

I did another clean installation of the theme files to ensure that I didn't make any changes. Attached is a screenshot of the network requests. 

<img width="395" alt="vue wp requests" src="https://user-images.githubusercontent.com/5210809/36644621-d10f20a8-1a2a-11e8-883d-4a85ec2e12a7.png">

**Comment by wester97** [comment]
Perhaps this is the wrong attachment? Go to Chrome > Inspector > Network
Then reload the page and let us know what you see.

**Comment by Ivanok** [comment]
@wester97 I uploaded the wrong attachment and changed it on the previous comment, am just now realizing that since you're responding via email that change did not get to you. Here is the correct attachment: 

![image](https://user-images.githubusercontent.com/5210809/36650472-b2bfa108-1a71-11e8-9d7f-7eb4924db164.png)

Thank you for the help.

**Comment by wester97** [comment]
Hmm, it seems that your requests for `pages` and `posts` aren't actually fired.

Do you see the placeholders for these sections on the homepage?  For example: Home.vue loads `pages-widget` which ultimately should load the results of `getPages` into the data store, and thus into the view.  You might have to trace that flow.

**Comment by Ivanok** [comment]
It works perfectly now!

Thank you.

**Comment by dedanirungu** [comment]
> I've worked out that adding '/development-vue' to my 'base' route (line 19 in index.js in the router folder) helps, as well as making sure 'plain' is not the chosen permalink. I've created a helper file to get `window.location.pathname` and I have added the result to router/index.js (modifying 'base' value) and also app.js modifying API_BASE_PATH). Working OK on MAMP.

I am having the same issue while trying to load pages. All pages are blank and only shows <div class="page-content-wrapper"></div>.

I have tried to follow the solution attached but I did not understand which files need to be changed.

@robwelan Kindly assist me with the steps guide on how to solve the issue.

**Comment by joshbedo** [comment]
Just downloaded the project and also having the same problem. I checked the network request and the API calls are returning the correct data and look fine but for some reason the body isn't rendering for posts/pages or home. I tried adding `debugger` in a few of the lifecycle methods but it wasn't getting hit not sure whats going on.

**Comment by EvanAgee** [comment]
I've just released an updated version of the project that will address many of these issues. Please note that the paths of the JS and CSS have changed so you may need to update your project. https://github.com/EvanAgee/vuejs-wordpress-theme-starter/issues/48
