### ISSUE TITLE
WordPress and VueJS routing problem

### ISSUE THREAD

**Issue by soroka-admin** [EvanAgee/vuejs-wordpress-theme-starter#127]
reload page not found 404  router ----    /slug/:id

**Comment by sotoyjuan** [comment]
Had the same problem with single post route. I fixed it by going to **wordpress dashboard > settings > permalinks** and selecting `Date and name` in common settings. Result:
`/%year%/%monthnum%/%day%/%postname%/`
Now it works well

**Comment by EvanAgee** [comment]
Yes @soroka-admin check out the [Getting Started](https://github.com/EvanAgee/vuejs-wordpress-theme-starter#getting-started) section, specifically number 4.
