### ISSUE TITLE
SEO impact?

### ISSUE THREAD

**Issue by hartey11** [EvanAgee/vuejs-wordpress-theme-starter#13]
Hi,

This looks great! Can't wait to try it out. Just wondering about SEO though. If we installed Yoast SEO for instance would this be enough as I assume the meta tags it adds to the head would still work as normal if every URL loads the index.php?

**Comment by raisiqueira** [comment]
@hartey11 @EvanAgee We can use the vue-meta to generate the meta tags, and fetch data from WP-API.

Example running in production:

![captura de tela 2018-01-15 as 16 54 19](https://user-images.githubusercontent.com/2914170/34959357-f1270012-fa14-11e7-9707-9d0ab9fba8ae.png)

and for keywords:

![captura de tela 2018-01-15 as 16 56 45](https://user-images.githubusercontent.com/2914170/34959399-1f7afe28-fa15-11e7-9e6b-90d8b228817c.png)

**Comment by EvanAgee** [comment]
@raisiqueira have you been able to get this to work with Facebook's Open Graph debugger? My understanding is that vue-meta (or generally altering the meta tags on the front-end) won't work because the crawlers won't wait for the scripts to execute.

**Comment by giekaton** [comment]
`vue-meta` doesn't work for facebook/twitter, it needs server side rendering or at least pre-rendering.

In the case of this paticular wp-vue repo, I think that you need to provide meta tags with wp, e.g. using Yoast plugin. Then fb will fetch these tags from php.

And for the client side you can use 'vue-meta' plugin, or do it without the plugin, like explained here: https://alligator.io/vuejs/vue-router-modify-head/

**Comment by giekaton** [comment]
Just tested this and can confirm that it works.

- Using `vue-head` for the client side. FB doesn't see this metadata.
- Using `Yoast SEO` plugin for Facebook, Twitter. Works great.
