### ISSUE TITLE
ERROR in ./src/app.js

### ISSUE THREAD

**Issue by Cobb-Zhang** [EvanAgee/vuejs-wordpress-theme-starter#131]
` Module build failed (from ./node_modules/babel-loader/lib/index.js):`
`Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in ...\vuejs-wordpress-theme-starter\node_modules\@babel\helper-compilation-targets\package.json`

when I run the `npm run watch`, the error above appear on the terminal

**Comment by E1NSER** [comment]
I had the same issue. Remove the package-json.lock. Update to the latest stable version of NPM and run `npm install` if you have done the `npm install` before, remove the node_modules folder before.

**Comment by Cobb-Zhang** [comment]
wow，thank you，it works！
