### ISSUE TITLE
npm ERR! missing script: build

### ISSUE THREAD

**Issue by Buda9** [EvanAgee/vuejs-wordpress-theme-starter#141]
after running npm install I run npm run build and got this err msg

```
npm ERR! missing script: build

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-02-14T22_05_27_768Z-debug.log
```

any ideas what to try next?

**Comment by JeromeDevillers** [comment]
Hi @Buda9 
I think you can add your own build script in `package.json` file. 

For now if you check the default file we don't have that command: 
https://github.com/EvanAgee/vuejs-wordpress-theme-starter/blob/master/package.json

Normally you can use the `npm run production` command as "build".
