### ISSUE TITLE
Wordpress web push notifications

### ISSUE THREAD

**Issue by abdokouta** [EvanAgee/vuejs-wordpress-theme-starter#21]
i'm using onesignal to push web notifications so how could i achieve that via vuejs as frontend i have looking over the web for web push api i have found this https://codecanyon.net/item/desktop-mobile-push-notification-system-wordpress-plugin/6548533 but to make it works i have to get this plugin first https://codecanyon.net/item/smio-wordpress-api-complete-solution/6448487 so are those plugins will works fine with wordpress and vuejs as frontend or do u suggest a solutions

**Comment by EvanAgee** [comment]
Howdy @abdokouta! One of the nice things about this project is that it's essentially just a VueJS app and therefore you can use any libraries you wish!
