### ISSUE TITLE
Firefox rendering

### ISSUE THREAD

**Issue by scheinercc** [EvanAgee/vuejs-wordpress-theme-starter#22]
Hi there,

While the page loads nicely in e.g. Opera and Safari, it looks really bad in Firefox for the first second (on a slower connection) while the page is loading.
![vuejs-wordpress_firefox-rendering](https://user-images.githubusercontent.com/817856/39964701-95d98dfe-56cd-11e8-9c26-b4d78a04d733.png)

Also, the Youtube video container has a scrollbar, which looks strange, especially just before the video has been setup. Interestingly enough this is not the case with active RDM.
![vuejs-wordpress_firefox-rendering_overlay](https://user-images.githubusercontent.com/817856/39964755-472dec34-56cf-11e8-923c-daf93b953f00.png)

**Comment by EvanAgee** [comment]
Thanks for the heads up!
