### ISSUE TITLE
Can't find assets ?

### ISSUE THREAD

**Issue by tsg1986** [EvanAgee/vuejs-wordpress-theme-starter#23]
Hi there, i'm trying to add assets (images and videos) directly form the theme but can't find a way to make it work. I tried several things, and feel a bit dumb, but I can't make it work and can't add a single image into theme ! So what is the best and proper way to do it ? (like the image already included in your theme)

**Comment by EvanAgee** [comment]
Hey @tsg1986 sorry for the delay, were you able to get it figured out?

Unfortunately I've not been able to arrive on a solution that I like that fits nicely with the webpack build process this project currently has. I've mostly resorted to providing fully qualified image URLs in my src files. It's not ideal, but it works.

**Comment by tsg1986** [comment]
Hi Evan, thanks for your answer ! I didn't figure it out, and had the same solution as yours. I don't have much static images so it will do the trick. Thanks for your work !
