### ISSUE TITLE
The theme shows up with no page content.

### ISSUE THREAD

**Issue by meera** [EvanAgee/vuejs-wordpress-theme-starter#25]
I could use a hint to get this theme working with WordPress.

- Brand new WordPress setup with no other plugin/themes. 
- Downloaded and extracted vuejs-wordpress-theme-starter Theme in wp-content\themes folder 
-- npm install and npm run production.
-- Activated the theme in wp-admin

I see header menu 'Link and Disabled' and footer 'This is the footer'.
However, I do not see the page content. 

Not sure why I do not see page content.  Wordpress is installed in a subdirectory so my wordpress url is http://localhost:8888/mywebsitefoldername

I tried to change API_BASE_PATH to point to /mywebsitefoldername/wp-json/wp/v2/

In Chrome Developer Console, I see http://localhost:8888/mywebsitefoldername/wp-json/wp/v2/pages?per_page=10 returns 200 with data.

**Comment by kingkyle** [comment]
Well since you are running it locally.. i think you need to run "npm run watch" and change the path "/" to "/mywebsitefoldername"

**Comment by EvanAgee** [comment]
Yes, what @kingkyle said, did you try running `npm run watch`?

**Comment by webprogrammingsolutions** [comment]
I'm having the same issue running on localhost with MAMP. Brand new install, no plugins, only starter theme selected.

http://localhost/wp/
Set API_BASE_PATH to /wp/wp-json/wp/v2/

Site loads header and footer, no errors reported. But no page content is loaded. It's like the router is just not loading the Home.vue as it should.

Please help! Really want to use this.

![screen shot 2018-07-27 at 9 20 44 pm](https://user-images.githubusercontent.com/5549215/43351047-f09a765e-91e2-11e8-9c22-888dd59bcbd9.png)

**Comment by EvanAgee** [comment]
Please re-check this issue. Today's release fixes several issues.
