### ISSUE TITLE
npm run production

### ISSUE THREAD

**Issue by questluv** [EvanAgee/vuejs-wordpress-theme-starter#28]
I got this error below when I try 'npm run production'. 

Is it any possibility to run your theme on the local server? 
As others mentioned,  no page content is loaded.

------------------------------------------------------------
ValidationError: UglifyJs Plugin Invalid Options

options should be object

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ production: `node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by EvanAgee** [comment]
This has been fixed with today's release!
