### ISSUE TITLE
Create a wordpress theme with VueJS incorporated

### ISSUE THREAD

**Issue by DavNej** [EvanAgee/vuejs-wordpress-theme-starter#30]
Hi,
I am building a custom theme in wordpress php and I would like to incorporate some vue components in it. I would like to keep wordpress' functionnality (login, register, custom post-types etc.) and its core php functions.

Is it possible to use Vue in some sections of some pages only, including the scripts in a php file and make vue run it instead of index.html (default in vue-cli) for example?

Thanks a lot :)

**Comment by EvanAgee** [comment]
@DavNej YES! This is actually what most devs are doing, I would say. You can create Vuejs components/apps that can easily be injected into a page. Typically these are done as plugins but you could also just make it part of the theme. Here's a great tutorial on setting one up https://deliciousbrains.com/vue-2-wordpress-plugin-tutorial/
