### ISSUE TITLE
Update  package.json

### ISSUE THREAD

**Issue by manacim** [EvanAgee/vuejs-wordpress-theme-starter#32]
vue => 2.5.17
vue-template-compiler => 2.5.17

After upgrading, I'm getting a bunch of errors. This is one of them:

`[Bootstrap-Vue warn]: b-nav: Prop 'is-nav-bar' is deprecated. Please use component '<b-navbar-nav>' instead.`

Did a fresh install and got this error:

> Vue packages version mismatch:

- vue@2.4.4
- vue-template-compiler@2.5.17
>

**Comment by EvanAgee** [comment]
@manacim I've just released an updated version of the project that will address many of these issues. Please note that the paths of the JS and CSS have changed so you may need to update your project. https://github.com/EvanAgee/vuejs-wordpress-theme-starter/issues/48
