### ISSUE TITLE
Handling assets

### ISSUE THREAD

**Issue by adamk22** [EvanAgee/vuejs-wordpress-theme-starter#33]
Hi @EvanAgee, first, thank you for the work! So far I've made it to good use but I'm wondering about how to handle assets, namely static images that sit in the dist folder.

I do have a solution which works, which is making a global variable to the directory and use it for static images in my template like so:

`Vue.prototype.$ASSET_DIR = "/wp-content/themes/theme-name/dist";`

and in my template
`
<img :src=" $ASSET_DIR + '/img/logo.svg'">
`

However, there must be a better way? Is there an asset handling provided by webpack that I'm missing here?

**Comment by EvanAgee** [comment]
Hey @adamk22 I think that's a perfectly fine solution! I've been doing some very similar myself!
