### ISSUE TITLE
Browsersync

### ISSUE THREAD

**Issue by TrilipuT** [EvanAgee/vuejs-wordpress-theme-starter#35]
Hi !
Thanks for great starter theme!
I'm wondering how can i use browsersync there? I found that laravel-mix support it but I can't make it work...

**Comment by EvanAgee** [comment]
@TrilipuT did you ever have any luck with this? I've had mixed results trying to use WordPress + Vue + Browsersync.

**Comment by TrilipuT** [comment]
Did not have time to do that... I will share when i have something :)
