### ISSUE TITLE
state.all.filter is not a function

### ISSUE THREAD

**Issue by Charles-antoine** [EvanAgee/vuejs-wordpress-theme-starter#37]
Hi,
I'm trying to use your theme starter but i'm confronted to this error:
-  state.all.filter is not a function
![screen shot 2018-10-29 at 5 00 58 pm](https://user-images.githubusercontent.com/21314112/47680090-442d4a00-db9c-11e8-9e95-7abdb97e3252.png)
Could you help me ?

**Comment by webadelic** [comment]
I'm seeing this also. Did you get a chance to investigate?

**Comment by EvanAgee** [comment]
Hey, sorry you're having issues. From what I can tell this could be happening because the list of pages hasn't yet been pulled from the WP API. I'm not sure when I'll have a chance to check it out but I'll have a look.

**Comment by webadelic** [comment]
Thanks, @EvanAgee. I'll be doing the same also, will update with my findings.

**Comment by rugor** [comment]
The array may be empty when filter is attempted. Try first checking array length with an if statement, something like:

`if (state.all.length) return state.all.find(page => page.id === id)`
