### ISSUE TITLE
Firebase version causes grpc clash

### ISSUE THREAD

**Issue by mortocks** [EvanAgee/vuejs-wordpress-theme-starter#42]
package.json defines     "firebase": "^4.13.1",
Current version of firebase is 5.6.0

installing with the old version on node v10.14.1 causes issues with the gRCP library.

**Comment by EvanAgee** [comment]
They've made lots of changes to Firebase since the initial release of this project. It might be best to ignore more Firebase boilerplate stuff and roll your own unfortunately.

**Comment by EvanAgee** [comment]
@mortocks I've just released an updated version of this project that removes the Firebase integration example.
