### ISSUE TITLE
assets not rebuilding with npm run watch

### ISSUE THREAD

**Issue by joshbedo** [EvanAgee/vuejs-wordpress-theme-starter#43]
Just noticing this but it seems like when files are changed witin the VueJS source code the project isn't recompiling. I keep saving and don't see the terminal re-run webpack processes or anything. Also having issues seeing changes on the theme once its activated as a theme on a wordpress install. Is their something i'm missing?

**Comment by joshbedo** [comment]
Looks like it might be related to issues with `laravel-mix`'s `copyDirectory` method i'm seeing a lot off issues around `npm run watch` currently open https://github.com/JeffreyWay/laravel-mix/issues

**Comment by EvanAgee** [comment]
Nice @joshbedo it might be time to remove laravel-mix and just go straight webpack. I'll have to take a look when I have some free time.

**Comment by joshbedo** [comment]
@EvanAgee so oddly enough i ran `npm cache clear --force`, delete .lock files, and reinstalled npm modules now its compiling fine. There are still some hiccups where it recompiles but the changes aren't there. I love the simplicity of the laravel-mix API but you might be right.

**Comment by joshbedo** [comment]
Thought i fixed this but the issue is back again :\

**Comment by joshbedo** [comment]
Which version of node are you using for this? @EvanAgee

**Comment by EvanAgee** [comment]
@joshbedo I've just released an updated version of the project that will address many of these issues. Please note that the paths of the JS and CSS have changed so you may need to update your project. https://github.com/EvanAgee/vuejs-wordpress-theme-starter/issues/48
