### ISSUE TITLE
ACF compatibility?

### ISSUE THREAD

**Issue by psntr** [EvanAgee/vuejs-wordpress-theme-starter#45]
Hi there,

Is is compatible with the ACF plugins?

**Comment by EvanAgee** [comment]
@psntr out of the box this project doesn't have any integration with ACF, however if you're familiar with Vue and the WordPress API it's fairly simple to integrate. You would need to update your WordPress JSON API so it outputs the ACF data (details here https://clarencepearson.com/advanced-custom-fields-rest-api/) and then update your Vue app to make use of that new data.
