### ISSUE TITLE
npm run watch issue

### ISSUE THREAD

**Issue by benoitvb** [EvanAgee/vuejs-wordpress-theme-starter#46]
I'm running npm run watch but I can't find where is the application running.
I tried localhost:8080 without success...
A laravel mix notification pops up but I don't know on which port the site it running.
Laravel is new to me and it looks a bit confusing....

**Comment by EvanAgee** [comment]
Thanks for reaching out @benoitvb this project isn't a Node app, its a WordPress theme. You would have to have a local instance of WordPress running already.

**Comment by benoitvb** [comment]
Thanks @EvanAgee I'll give it a try and let you know !
