### ISSUE TITLE
npm install returns a list of errors

### ISSUE THREAD

**Issue by MarcRuemekorf** [EvanAgee/vuejs-wordpress-theme-starter#47]
Hi Evan, 

I'm having trouble getting your theme up and running. I installed Wordpress on a local (MAMP) server and simply copied the theme files to my theme directory and took things from there. Following the quickstart video and the readme file I tried running `npm install` inside the theme directory. This in turn just gave me a bunch of errors right off the bat. What could I be doing wrong?

**Comment by Quorong** [comment]
I just spent the better part of a day getting this to run locally. I ran into problems with trying to build the node-gyp dependency on Node 10.0.0+ on Windows. I finally got it working though, maybe I can help.

1) Are you trying to run this on Windows?

2) What do the errors you get look like?

**Comment by MarcRuemekorf** [comment]
Hi Quorong,

Thanks for your reply and help of course! Let's see:

1. No I'm running on Mac
I run a local (apache) server using Mamp Pro.

2. It's a whole list of errors just by trying to install NPM here's a couple:

- `xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory`
- `rm: ./Release/.deps/Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o.d.raw: No such file or directory` followed by a couple gyp ERR's
- and a `fatal error: 'grpc/slice.h' file not found`
- It ends with this line `This is probably not a problem with npm. There is likely additional logging output above.`

There quite a bit more of these errors, mostly gyp ERR, is there a specific error you're looking for? I have been using NPM for a couple of Wordpress websites so I'm sure it's up-to-date. Yarn seems to be an option too but that isn't installed correctly on my machine (yet) hence the NPM route. Would that be a viable option? In the quick start video he simply runs `Yarn run build`. If all it takes is to correctly configure Yarn I'll do that.

**Comment by EvanAgee** [comment]
@MarcRuemekorf I've just released an updated version of the project that will address many of these issues. Please note that the paths of the JS and CSS have changed so you may need to update your project. https://github.com/EvanAgee/vuejs-wordpress-theme-starter/issues/48

**Comment by MarcRuemekorf** [comment]
@EvanAgee Awesome! Thanks Evan I'll check it out.

**Comment by MarcRuemekorf** [comment]
That did it! Thanks for the update @EvanAgee
