### ISSUE TITLE
Is this compatible with Carbon fields?

### ISSUE THREAD

**Issue by joannesalfa** [EvanAgee/vuejs-wordpress-theme-starter#49]
https://carbonfields.net

It's awesome library you can easily add custom fields as gallery, nested list, widget, gutenberg block, etc.
Basically you add something in function.php then pass a variable into any wordpress page template.... but how do you store php variables into vue.js data?

In that case it's a php code `carbon_get_theme_option( 'crb_myName_field' );`

**Comment by EvanAgee** [comment]
@joannesalfa you would accomplish this by updating the WordPress REST API to include that data here's a guide on how to do so [https://developer.wordpress.org/rest-api/extending-the-rest-api/modifying-responses/]. There are also a number of WordPress plugins that allow you to control the API output.

**Comment by joannesalfa** [comment]
What's kind of plugin would you recommend me? specifically for theme folder without asking the users to find and install a plugin.
