### ISSUE TITLE
Integrate Vuetify rather than Bootstrap

### ISSUE THREAD

**Issue by jtlevy** [EvanAgee/vuejs-wordpress-theme-starter#50]
Curious if you had any thoughts about replacing Bootstrap with Vuetify. I may be pursuing that path, and was looking at your project to gleen some Vue + WP insight.

**Comment by EvanAgee** [comment]
@jtlevy thanks for the question! I actually just removed Bootstrap Vue from the latest release for the same reason I would be hesitant to use Vuetify; the purpose of this project is to be a starting point for devs and both of those UI frameworks are a little too heavy-handed for my liking. I also believe they're both easy enough to add to a project that most people wouldn't need it included as a default.

Let me know if you need anything, thanks!
