### ISSUE TITLE
Preview button?

### ISSUE THREAD

**Issue by jonaseltes** [EvanAgee/vuejs-wordpress-theme-starter#51]
Sorry for assuringly stupid question but is there any chance this setup allows for a functioning preview button? Or any planned workarounds/integrations?

Thanks!

**Comment by EvanAgee** [comment]
Not a stupid question at all @jonaseltes. While this is not currently supported in this theme it would be possible if WordPress exposes those previews via the REST API, I'm not sure if they do or not.
