### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by wesleydeveloper** [EvanAgee/vuejs-wordpress-theme-starter#52]
In my build I'm getting the following TypeError error: "t.all.filter is not a function"

**Comment by giekaton** [comment]
Same here. And doesn't load the content, only header and footer.

[Vue warn]: Error in render function: "TypeError: t.all.filter is not a function"

**Comment by wesleydeveloper** [comment]
It is not a mistake, you have to go in settings and change the api path and also go on routes and do the same
