### ISSUE TITLE
Question with woo

### ISSUE THREAD

**Issue by zkenstein** [EvanAgee/vuejs-wordpress-theme-starter#54]
Is it compatible with woocommerce?

**Comment by EvanAgee** [comment]
@zkenstein you've likely moved on by now but I did want to comment on this just in case it's helpful to anyone else. This theme isn't really "compatible" with anything other than WordPress, however you can easily connect to the WooCommerce API endpoints within your Vue components and grab any data you'd like and do as you please. They have an extensive JS API so you could in theory completely recreate the whole store functionality in Vue. That, however, is outside of the scope of this project.
