### ISSUE TITLE
Adding WordPress menus to Vue

### ISSUE THREAD

**Issue by EvanAgee** [EvanAgee/vuejs-wordpress-theme-starter#60]
Finally created a video on adding support for WordPress menus https://www.youtube.com/watch?v=fa_muCUHUuM

**Comment by jonaseltes** [comment]
Thanks for super helpful tutorial! There seems to be quite some loading times for the menu items in your demo, is there any specific reason for this and any way to avoid it? (Didn't try it out myself yet)

Thanks!

**Comment by EvanAgee** [comment]
Thanks @jonaseltes the reason it was loading slowly in my demo was because I was running on a local docker instance with limited resources. It should be substantially faster if you're on a decent host. Have fun!
