### ISSUE TITLE
The menu setting invisible under appearance

### ISSUE THREAD

**Issue by xmqywx** [EvanAgee/vuejs-wordpress-theme-starter#62]
WP Version: 5.2.2
Issue: The 'Menu' disappeared under appearance menu.(Appearance -> Menu option is not showing)
Solution: Add `add_theme_support( 'menus' );` code in `functions.php`
💯

**Comment by Tes3awy** [comment]
It's required to add the `add_theme_support(  'menus'  )` into the `function.php` file. Here is a snippet which you can add to show the `Appearance > Menu` item.

```php
add_theme_support('menus');
add_action('init', 'register_my_menu');
function register_my_menu()
{
    register_nav_menu('header-menu', __('Navigation Menu'));
}
```
You might also want to show the Featured Image, and you can do so by adding only this line:

```php
add_theme_support( 'post-thumbnails', array( 'post' ) );
```
You can also add `'page'` within the array.

Feel free to close the issue.
