### ISSUE TITLE
Vuex Setup

### ISSUE THREAD

**Issue by Tes3awy** [EvanAgee/vuejs-wordpress-theme-starter#63]
Can you please provide me with some steps to start using Vuex? I didn't edit any file within the `store` directory. However; after the setup, I get this error `Error in the created hook: "TypeError: Cannot read property 'get' of undefined"` in the browser's console. This error is caused by the following two lines in the `created` life-cycle hook in the parent Vue instance.

```js
new Vue({
  router,
  store,
  render: (h) => h(App),
  created() {
    this.$store.commit(types.RESET_LOADING_PROGRESS);
    this.$store.dispatch('getAllCategories'); // This one
    this.$store.dispatch('getAllPages'); // And this one as well
  }
}).$mount('#app');
```
Can you please guide me solve this problem? I am really grateful for this amazing work. Thank you so much.

**Comment by EvanAgee** [comment]
Hey @Tes3awy I'm guessing this error is actually being triggered in this file: https://github.com/EvanAgee/vuejs-wordpress-theme-starter/blob/master/src/api/index.js are you still importing axios?

**Comment by Tes3awy** [comment]
@EvanAgee Yes, I am still importing axios

**Comment by Tes3awy** [comment]
I figured out the problem. I didn't provide the correct path in `settings.js` file. I'll also add some instructions to the `README.md` file to help others.
