### ISSUE TITLE
How to add Vuetify?

### ISSUE THREAD

**Issue by ajotka** [EvanAgee/vuejs-wordpress-theme-starter#69]
Hi! 
I'm trying to add the Vuetify library in 2.0.11 version, but I have few errors in dev console. I have no idea how to fix it. I was trying to add 'a-la-carte' version and 'full' version, but still the same errors. 

Ps. It's a fresh installation. Theme Version: 4.0.4

_// src/main.js (also I tried with src/app.js)_
```require("./bootstrap");
import Vue from "vue";

import router from "./router";
import App from "./App.vue";
import store from "./store";
import vuetify from './plugins/vuetify';
import * as types from "./store/mutation-types";

import "./assets/css/styles.css";

new Vue({
  el: "#app",
  store,
  router,
  vuetify,
  render: h => h(App),
  created() {
    this.$store.commit(types.RESET_LOADING_PROGRESS);
    this.$store.dispatch("getAllCategories");
    this.$store.dispatch("getAllPages");
  }
});
```

_// src/plugins/vuetify.js_
```import Vue from 'vue';
import Vuetify from 'vuetify';

const opts = {
    icon: {
        iconfont: 'mdi',
    }
};
Vue.use(Vuetify);

export default new Vuetify(opts);
```

And in _src/App.vue_ I changed `<div id="my-app" class="page-wrapper">` to `<v-app id="my-app" class="page-wrapper">`

==============

Errors: 

```
[Vue warn]: Injection "theme" not found

found in

---> <VApp>
       <Anonymous>
         <Root>
ms @ index.min.bundle.js?ver=1567150614:11
index.min.bundle.js?ver=1567150614:11 
```
```
[Vue warn]: Error in getter for watcher "isDark": "TypeError: Cannot read property 'dark' of undefined"

found in

---> <VApp>
       <Anonymous>
         <Root>
ms @ index.min.bundle.js?ver=1567150614:11
index.min.bundle.js?ver=1567150614:11 TypeError: Cannot read property 'dark' of undefined
    at a.isDark (index.min.bundle.js?ver=1567150614:41)
    at Co.get (index.min.bundle.js?ver=1567150614:11)
    at Co.evaluate (index.min.bundle.js?ver=1567150614:11)
    at a.isDark (index.min.bundle.js?ver=1567150614:11)
    at a.<anonymous> (index.min.bundle.js?ver=1567150614:11)
    at Co.get (index.min.bundle.js?ver=1567150614:11)
    at new Co (index.min.bundle.js?ver=1567150614:11)
    at a.e.$watch (index.min.bundle.js?ver=1567150614:11)
    at Qt (index.min.bundle.js?ver=1567150614:11)
    at Jt (index.min.bundle.js?ver=1567150614:11)
```

==============

What is on frontend?
Blank page with WP Admin Bar. WP Query Monitor doesn't show any errors.

**Comment by EvanAgee** [comment]
Hello @ajotka adding Vuetify to this project is relatively straightforward and it actually use to be part of the core of this project. There shouldn't be anything specific to this project that makes it challenging.

**Comment by Maciejkoson** [comment]
Hello well, i did today add vuetify, i had some problems, first of all update all node packages and then start to add like they show here https://vuetifyjs.com/en/getting-started/quick-start

**Comment by devrobinkroeker** [comment]
Hey @EvanAgee I am currently trying to install vuetify and I am struggling hard with webpack (at least I think it's webpack). When I follow this guide (https://vuetifyjs.com/en/getting-started/quick-start) and add all the necessary lines in webpack.config.js and then try to run `npm run watch` I get a long error message. As I am not an experienced user of webpack I wanted to ask if you have an idea of what could be the problem that the command isn't working anymore?! (btw. thanks for the awesome project)

Here the important part of the error message:
![Screenshot 2019-12-04 at 08 18 23](https://user-images.githubusercontent.com/44995063/70121853-b9a4fd00-166f-11ea-92fa-43e8149ce0a1.png)

Thanks in advance

**Comment by EvanAgee** [comment]
@devrobinkroeker  did you ever get this working?

**Comment by devrobinkroeker** [comment]
@EvanAgee Unfortunately not. But I didn't give up. I'm still trying ... :)
