### ISSUE TITLE
What is port number? 

### ISSUE THREAD

**Issue by ejoo** [EvanAgee/vuejs-wordpress-theme-starter#7]
I cannot access with http://localhost:8080/.

**Comment by vikash2039** [comment]
hopefully there can be any port for your project but you can use this as theme in wordpress , just run `npm run watch` (if you are using npm) or if your are using yarn then `yarn run watch` in root directory,  it will watch for changes in `./src` directory and directly compile it to `./dist/`

**Comment by EvanAgee** [comment]
Hey @ejoo in this case webpack-dev-server isn't running the Wordpress instance, it's just being used to build the theme. So you'll need to run your Wordpress instance on whatever stack you normally would and then run the dev server to build your theme changes. Hope that helps!
