### ISSUE TITLE
Deprecated dependencies

### ISSUE THREAD

**Issue by richj88** [EvanAgee/vuejs-wordpress-theme-starter#76]
Hi when I run npm install I am receiving these warnings -- 

`npm WARN deprecated postcss-cssnext@3.1.0: 'postcss-cssnext' has been deprecated in favor of 'postcss-preset-env'. Read more at https://moox.io/blog/deprecating-cssnext/

npm WARN deprecated extract-text-webpack-plugin@3.0.2: Deprecated. Please use https://github.com/webpack-contrib/mini-css-extract-plugin

npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.

npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.

npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.

npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.

npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
`

Im new to this so Im unsure what to do at this point. I don't want to mess with things and break the theme. How can I fix this?

**Comment by EvanAgee** [comment]
@richj88 I'm in the process of fixing now, thanks!

**Comment by EvanAgee** [comment]
@richj88 all updated now!
