### ISSUE TITLE
Vue-cli

### ISSUE THREAD

**Issue by patleeman** [EvanAgee/vuejs-wordpress-theme-starter#8]
Hey Evan,

This is a great project, exactly what I've been searching for!

Have you considered creating a repo that's compatible with [Vue-cli](https://github.com/vuejs/vue-cli)? It would make it a cinch to bootstrap new projects using this starter theme.

**Comment by EvanAgee** [comment]
That's a good idea @patleeman. I hadn't thought of it but I'll definitely look into it.

**Comment by EvanAgee** [comment]
Feel free to open a PR too if you have the time
