### ISSUE TITLE
Read permalink structure from Wordpress configuration

### ISSUE THREAD

**Issue by PeterNerlich** [EvanAgee/vuejs-wordpress-theme-starter#86]
for now hard coded to default: https://github.com/EvanAgee/vuejs-wordpress-theme-starter/blob/1350eef4a5470d3e2f6e7a4972795527a5c5f03e/src/router/index.js#L21

**Comment by EvanAgee** [comment]
@PeterNerlich I'm updating the docs to note that this will need to be updated if you want to use a different permalink structure.
