### ISSUE TITLE
Is this a starte kit where no posts and no pages will be rendered?

### ISSUE THREAD

**Issue by nise** [EvanAgee/vuejs-wordpress-theme-starter#88]
In Wordpress 5.3.x only the header and the footer will be visible. 

The API endpoint 127.0.0.1/eckingen/wp-json/wp/v2/ depends on the permalink settings. If one is not using pretty links the src/settings.js should point to '/?rest_route=/' instead. 

However, some documentation is missing in order to run the plugin in Wordpress. At least people like me who know Vue better then WP would need some more support here.

Thank you.

**Comment by harrisonfm** [comment]
To get pages and posts on a fresh WP install you need to set your WP Permalinks to be Y/M/D/slug.  This is the second option in the Permalinks section of the WP-admin. You can edit the router as well.

This would be a good thing to mention in the Readme.

**Comment by EvanAgee** [comment]
I'll update the readme now, thanks!

**Comment by nise** [comment]
Great, thank you!
