### ISSUE TITLE
How to use devtools debugger?

### ISSUE THREAD

**Issue by mhartz** [EvanAgee/vuejs-wordpress-theme-starter#89]
Just started testing this out and it looks great. My only issue is that there is only the bundled JS referenced in the page. Is there any way to debug the Vue files themselves? I would like to set breakpoints to debug vs. console.log'ing everything out.

Note: I can use the Vue Debugging Chrome extension. This is just with the default Chrome devtools.

**Comment by EvanAgee** [comment]
@mhartz yes! As long as you're running your watcher it runs in dev mode which will enable the Vue devtools.
