### ISSUE TITLE
WP Menu via WP-API

### ISSUE THREAD

**Issue by raisiqueira** [EvanAgee/vuejs-wordpress-theme-starter#9]
Hi! for the menus via WP-API, we can use [WP Rest API Menus](https://br.wordpress.org/plugins/wp-rest-api-v2-menus/), but we have a problem. The endpoint don'ts `/wp-json/wp/v2/`, is `/menus/v1/menus`.

Possible solution: In the `app.js` file, change the `API_BASE_PATH` for only `/wp-json`, instead of: `/wp-json/wp/v2/`.

done that, we created a module to get the menu with vuex. 😄 

I'm using it that way, but with NuxtJS. Can I make a pull request?

**Comment by itjunkii83** [comment]
I would really like to see this working. New to Vue and struggling quite a bit on how to create new routes from my Wordpress menu.

**Comment by EvanAgee** [comment]
Yes, PLEASE make a pull request @raisiqueira
