### ISSUE TITLE
On new installation, theme doesn't work (t.all.filter is not a function)

### ISSUE THREAD

**Issue by DevJulia** [EvanAgee/vuejs-wordpress-theme-starter#90]
Hello,

I want to practice VueJS by creating a SPA with Wordpress. Your theme seems perfect for that.
However, after I installed it, the homepage is empty [https://ibb.co/Qj9fDLZ](https://ibb.co/Qj9fDLZ). 

In the Vue DevTools, I have the error pageContent:"(error during evaluation)".
In the browser Devtools, I have the following error : [Vue warn]: Error in render function: "TypeError: t.all.filter is not a function"

How can I fix this?

Thank you.
Julia

**Comment by Dizolivemint** [comment]
Same.

Ah, found the solution in issue #52!

**Comment by EvanAgee** [comment]
@DevJulia as @Dizolivemint  pointed out there's a solution here https://github.com/EvanAgee/vuejs-wordpress-theme-starter/issues/52
